# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 05:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cumulativeAmount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='homeAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="'-'를 제외하고 010xxxxxxxx 형식으로 입력해주세요", regex='^010\\d{4}\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
