# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0002_auto_20170817_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cumulativeAmount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
