# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0003_auto_20170817_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bigCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.BigCategory'),
            preserve_default=False,
        ),
    ]
