# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0004_auto_20170817_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='bigCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.BigCategory'),
            preserve_default=False,
        ),
    ]
