# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0006_auto_20170817_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dcprice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
