# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0007_auto_20170817_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homeAddress',
            new_name='location1',
        ),
        migrations.AddField(
            model_name='profile',
            name='location2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
