# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0008_auto_20170817_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location1',
            new_name='detailAddress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location2',
            new_name='streetName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location3',
            new_name='subAddress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location4',
            new_name='zipCode',
        ),
    ]
