# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0009_auto_20170817_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
