# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0010_auto_20170819_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
