# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0012_cart_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.Profile'),
        ),
    ]
