# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0014_auto_20170820_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalPrice',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
