# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0015_cart_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
