# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0018_auto_20170822_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingmall.Profile'),
        ),
    ]
